spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3ZBb0NEVkpRdE1QczQrTEQKNjJTTkxYOUdIelpuWm91aXFMRm5QR2xZbWZXaFJBTkNBQVFKVlpHaVdoSDhQRDZNb3VabFEzeEpCZXhSTUNISApyTllyNWNabWZnVXFodFVERzZNeEZsZDNadDJjRFIxbU5hL1JvdFVTS2NnVGJ4a3lHRmdGVlFySwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNTVENDQWUrZ0F3SUJBZ0lRUy96bTdNRXNCWjRVTENMVFpycXpTakFLQmdncWhrak9QUVFEQWpDQml6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1UQXdMZ1lEVlFRTERDZGhaRzVmTmpJMgpRRXhCTFV0Q1QwWkJMVEkxTURBd0lDaEJaRzVoYm1VZ1NHRmthbUZrYWlreE56QTFCZ05WQkFNTUxtMXJZMlZ5CmRDQmhaRzVmTmpJMlFFeEJMVXRDVDBaQkxUSTFNREF3SUNoQlpHNWhibVVnU0dGa2FtRmthaWt3SGhjTk1qWXcKTkRFMU1UTXlNVFUwV2hjTk1qZ3dOekUxTVRNeU1UVTBXakJiTVNjd0pRWURWUVFLRXg1dGEyTmxjblFnWkdWMgpaV3h2Y0cxbGJuUWdZMlZ5ZEdsbWFXTmhkR1V4TURBdUJnTlZCQXNNSjJGa2JsODJNalpBVEVFdFMwSlBSa0V0Ck1qVXdNREFnS0VGa2JtRnVaU0JJWVdScVlXUnFLVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUEKQkFsVmthSmFFZnc4UG95aTVtVkRmRWtGN0ZFd0ljZXMxaXZseG1aK0JTcUcxUU1ib3pFV1YzZG0zWndOSFdZMQpyOUdpMVJJcHlCTnZHVElZV0FWVkNzcWpaREJpTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLCkJnZ3JCZ0VGQlFjREFUQWZCZ05WSFNNRUdEQVdnQlRkQjBUQ2hnNHE0QjB0YWdsbHlpZnBXYUdTUHpBYUJnTlYKSFJFRUV6QVJnZzlzYjJOaGJDNHdlR1JpWlM1a1pYWXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWdKMEhiTkxuaApvaFk0THNLV0JuOUZ5dEpHdmNJVWx0eUFtZXZkY1NGekhGQUNJUUQ3K0M3VlV1T0VJaXc5b3h6eTE5MmRvUnl4CjNYb01DbXlBOXBYcDFINmhiZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXekNDQWdLZ0F3SUJBZ0lSQUlnVVJzamdRZjlaQ1J6Wll3eUpCQk13Q2dZSUtvWkl6ajBFQXdJd2dZc3gKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURXdNQzRHQTFVRUN3d25ZV1J1WHpZeQpOa0JNUVMxTFFrOUdRUzB5TlRBd01DQW9RV1J1WVc1bElFaGhaR3BoWkdvcE1UY3dOUVlEVlFRRERDNXRhMk5sCmNuUWdZV1J1WHpZeU5rQk1RUzFMUWs5R1FTMHlOVEF3TUNBb1FXUnVZVzVsSUVoaFpHcGhaR29wTUI0WERUSTIKTURReE5URXpNVGt6TVZvWERUTTJNRFF4TlRFek1Ua3pNVm93Z1lzeEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCawpaWFpsYkc5d2JXVnVkQ0JEUVRFd01DNEdBMVVFQ3d3bllXUnVYell5TmtCTVFTMUxRazlHUVMweU5UQXdNQ0FvClFXUnVZVzVsSUVoaFpHcGhaR29wTVRjd05RWURWUVFEREM1dGEyTmxjblFnWVdSdVh6WXlOa0JNUVMxTFFrOUcKUVMweU5UQXdNQ0FvUVdSdVlXNWxJRWhoWkdwaFpHb3BNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRApRZ0FFcXM3NHNyenFRV3lZZkFoNU9tTlNpWmxzNklZWTZ1VGc3NTlsVWhMZFVsQ2Qrc3dadTlYaklMVFBmai93Cm1oTzVZQ1hvak5nYXhZd2UzbFpHdnZ3QVphTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnSUVNQklHQTFVZEV3RUIKL3dRSU1BWUJBZjhDQVFBd0hRWURWUjBPQkJZRUZOMEhSTUtHRGlyZ0hTMXFDV1hLSitsWm9aSS9NQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUZNTjI4NFM0SldDMWFpMEdGNmZ3dm90ekhybmR6UDdlVDJadFBERDVwZHhBaUFICkFFc3dsOTk1TGxXOGxRS3U3d2oza0ZmcFpGeGNGWXZlak1HR3ZDUytJUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

  # Step 1a: End of SSL configuration

server:
   # Step 1b: Enable SSL and specify ssl bundle
  port: 8443
  ssl:
    bundle: web
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  servlet:
    session:
      cookie:
        same-site: strict
        secure: true
  # Step 5: End of session cookie configuration