name: security

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Upload OSV SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: DependenciesAnalysisFull.sarif

  source-code-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config .semgrep \
            --sarif \
            --output SourceCodeAnalysis.sarif
        continue-on-error: true

      - name: Upload Semgrep SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: SourceCodeAnalysis.sarif
